#include <lcom/lcf.h>

xpm_row_t cat_01[] = {
"80 30 13 1",
"  c #000000",
". c #FFFFFF",
"X c #FF0000",
"o c #918889",
"O c #F8BBD2",
"+ c #9E11FA",
"@ c #4657EA",
"# c #0290DC",
"$ c #09BD05",
"% c #F7C502",
"& c #4E4640",
"* c #E9322B",
"= c None",
"==*******=========********=========*********==                       ===========",
"=XXXXXXXXX========XXXXXXXX*=======*XXXXXXXXXX=&&&&&&&&&&&&&&&&&&&&&&&&==========",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  OOOOOOOOOOOOOOOOOOOOOO.o =========",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX &OOOOOOOOOOOOOOOOOOOOOOOOOo ========",
"X*********XXXXXXXX********XXXXXXXXX******** &OOOOOOOOOOO*OOO*OOOOOOOOOO ========",
"*%%%%%%%%%X*****X*%%%%%%%%*X*****X*%%%%%%%% &OOOOOOOOOOo*OOO*OOOOOOOOOo ========",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOO*oOOOOOOOOOOOOOOOOOOo ========",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OO**OOOOOOOOOOO.& &.O*OOOo ====  ==",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OO*oOOOOOOOOOOOo&  o*oOOOo === &&==",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOOOOOOOo &Oo o.OOOo == oOo =",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOOOOOOOo &ooo &...O   oooo =",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOOooOOOo &ooo&&&&&& &&oooo =",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOO**OOOO &ooooo     oooooo =",
"%$$$$$$$$$%%%%%%%%$$$$$$$$%%%%%%%%%$$$$$$$$ &OOOOO*oOOOOOO.O &oooooooooooooooo =",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  &OOOOOOOOOOo*Oo ooooooooooooooooooo ",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ $$&& &OOOOOOOOOOO*O& ooooOo&oooooooO&&oo&",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    &o &OO**OOOOOOOOO& oooo.& ooooooo.  oo&",
"$$########$$$$$$$$########$$$$$$$$$  &ooooo &OOOOOOOOOOOOO& oooo   oooo &o  &oo&",
"$#################################& &ooo&&& &OOOOOOOO*OOOO& ooOo&&ooooo&oo&&oOO&",
"################################### oo&o    &OOOOOOOO*OOO.& oOOOooooooooooooOO.&",
"####################################     &# &OOOo*OOOOOOO.& oOOOo  oo& oo& &OO.&",
"#@+++++++@########@+++++++@#########@++++++ &.OOOOOOOOOOO*oo oOoo          &Oo&=",
"@+++++++++@@@@@@@@++++++++@@@@@@@@@@+++++++ &oOOO.OOOOOOO*OO&&&oo&&&&&&&&&&oo& =",
"+++++++++++++++++++++++++++++++++++++++++++   OOOOOOOOOOOOOOO  ooooooooooooo& ==",
"+++++++++++++++++++++++++++++++++++++++++++ &o                              ====",
"++========++++++++========++++++++++======= &o&  = &o&  ===== &oo  ==== &o& ====",
"+=========++++++++=========+++++++++======= &oo == &oo =======&oo  ==== &oo ====",
"===========================================    =====    =======    =====     ===",
"================================================================================",
"================================================================================"
};

xpm_row_t cat_02[] = {
"80 30 13 1",
"  c #000000",
". c #FFFFFF",
"X c #FF0000",
"o c #8F8889",
"O c #F8B8CF",
"+ c #A00FFC",
"@ c #376AEE",
"# c #048DDD",
"$ c #0CBD07",
"% c #F9C402",
"& c #48403C",
"* c #ED3421",
"= c None",
"X*=======*XXXXXXXX========XXXXXXXXX=============================================",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=                        ==========",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX& OOOOOOOOOOOOOOOOOOOOOOOo =========",
"*XXXXXXXX*********XXXXXXXX*********XXXXXXXX&&oOOOOOOOOOO.OOO.OOOOOOOOOo ========",
"%*********%%%%%%%%********%%%%%%%%%******** &.OOOOOOOOOOOOOOOOOOOOOOOO.& =======",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOOOO*O.O*oOOOOOOOOO& =======",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOO*oOOOOOOOOOO..OOOOOOO& =======",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOO*oOOOOOOOO.OooOOOOOOO& =======",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OO**OOOOOOOOOOO.&  oO*OOOO& ===  ==",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOOOOOOOO &oo &.OOOO& = &oo& ",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOOOOOOOO &oo&&&O.OO&  &ooo& ",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% &OOOOOOOOOOOOOOO &ooo& oOoo&  oooo& ",
"$%%%%%%%%$$$$$$$$$%%%%%%%%$$$$$$$$$  &%%%%% &OOOOOOOOO**OOOO &ooooo     &ooooo& ",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ &&o&&$$$$ &OOOOO*oOOOOOO.O &ooooo&&&&&oooooo  ",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ &OO& $$$$ &OOOOO*oOOOOOOOo&&oooooooooooooooo& ",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  oo&      &OOOOOOOOOOO*Oo oooooooooooooooooooo",
"#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$& ooooooo &OO**OOOOOOOOOo oooo.O ooooooo.o oo&",
"###################################&&&&oooo &OOOoOOOOOOOO.o ooooo& oooo&&oo& oo&",
"####################################   oooo &OOOOOOOOOOOO.o oooo   oooo  o  &ooo",
"#######################################     &OOOOOOOO*oOO.o oOOOoooooooooooooO.o",
"+########################################## &OOOO*OOOOOOO.o oOOOo&&ooo&ooo&&oO.O",
"+@@@@@@@@@++++++++@@@@@@@@++++++++++@@@@@@@ &OOOO*OOOOOOOOo&&oOOo& &o& &o& &oOOo",
"+++++++++++++++++++++++++++++++++++++++++++ &OOOOOOOOOOOO*O. &ooo&         &oo  ",
"+++++++++++++++++++++++++++++++++++++++++++  &OOOOOOOOOOOOOOO& oooooooooooooo ==",
"=+++++++++++++++++++++++++++++++++++++++++&&&&&&&&&&&&&&&&&&o& &&&&&&&&&&&&&& ==",
"=++++++++=========++++++++==========++++++ oOo                                ==",
"========================================== oOo ===== ooo ====== ooo ===== ooo ==",
"========================================== &&&=======&&& =======&&& ======&&& ==",
"================================================================================",
"================================================================================"
};

xpm_row_t cat_03[] = {
"80 30 13 1 ",
"  c #000000",
". c #FFFFFF",
"X c #F30B12",
"o c #AF8E90",
"O c #FABDD9",
"+ c #352E32",
"@ c #A00EFA",
"# c #6D3AF4",
"$ c #058BE4",
"% c #03BC08",
"& c #F3C101",
"* c #7E776D",
"= c None",
"================================================================================",
"=XXXXXXXX=========XXXXXXXX=========XXXXXXXXX==                       ===========",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+=***********************+==========",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+*.OOOOOOOOOOOOOOOOOOOOO.*+=========",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX oOOOOOOOOOOOOOOOOOOOOOOOOOo ========",
"X&&&&&&&&XXXXXXXXX&&&&&&&&XXXXXXXXX&&&&&&&& *OOOOOOOOOOoXOOoXOOOOOOOOOo ========",
"X&&&&&&&&&XXXXXXXX&&&&&&&&XXXXXXXX&&&&&&&&& *OOOOOoOOOOooOOooOOOOOOOOOo ========",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& *OOOOOXoOOOOOOOOOOOOOOOOOOo ========",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& *OOXoOOOOOOOOOOOO  +.XoOOOo ===   ==",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& *OOoOOOOOOOOOOOo+++++oOOOOo ===+*+==",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& *OOOOOOOOOOOOO.* oo* *OOOOo ==+oo* =",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& *OOOOOOOOOOOOOO* *o*o +.OOo  +o*o* =",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& *OOOOOOOOOXoOOO* *o***++    +*o*o* =",
"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&+**&&&&% *OOOOOoOOOoOOO.o *o**o*+++++*o**o* =",
"&%%%%%%%%%&&&&&&&&%%%%%%%%&&&&&&&&+    %%%% *OOOOOXoOOOOOOO* *o***oooooo****o* =",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% +oo+      *OOOOOOOOOOoXO+ o****oo********oo**+",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  +o****+  *OOooOOOOOOOoO+ o**o.*+o***o*o.++oo+",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   ****o++ *OOXoOOOOOOOOO+ o**oO  o*****oO +o*+",
"%$$$$$$$$%%%%%%%%%$$$$$$$$%%%%%%%%%%     *o *OOOOOOOOOOOOO+ o*o*  +o*o* *+  +o*+",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    *OOOOOOOoXOOOO+ oOOo*****oo*****oOO+",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$+++ *OOOOoOOOoOOO.  oOOOo**oo*+oo***OO.+",
"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ *OOOoXOOOOOOOO+ oOOOo  oo+ *o+ *OOO+",
"$#@@@@@@@#$$$$$$$$@@@@@@@@$$$$$$$$$$@@@@@@@ o.OOOOOOOOOOOXO* oo*o          *o* =",
"#@@@@@@@@#########@@@@@@@@##########@@@@@@+ +*.OOOOOOOOOOoOOo+*oo****++****o* ==",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+    ooooooooooooooo +*******X*****+===",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                    ====",
"@========@@@@@@@@@========@@@@@@@@@@=== ***o+ ==== +o*  ===== +o*+ ==== +** ====",
"======================================= ooo*+======+** =======+**  ==== *Oo ====",
"======================================= *o* ========   ========   ===== *o* ====",
"=======================================    =============================    ===="
};
