#ifndef __vbe2__
#define __vbe2__

#define VBE_VERSION_SELECT_PORT  0xAH
#define ENABLE_VBE2      0x4F

#define VBE_FUNCTION_IS_SUPPORTED 0x4F
//VBE RETURNS:
#define VBE_FUNCTION_SUCCESS 0x00
#define VBE_FUNCTION_FAILED  0x01
#define VBE_FUNCTION_HARDWARE_NOT_SUPPORTED 0x02
#define VBE_FUNCTION_INVALID_VIDEO_MODE 0x03

//VBE MODE
#define VBE_FUNC_GET_MODE 0x01
#define VBE_FUNC_SET_MODE 0x02


#define LINEAR_FRAME_BUF BIT(14)


#define VBE_MODE_CGA  0x03 //standard minix text mode

#define VBE_MODE_INDEXED 0x105
#define VBE_MODE_DIRECT_COLOR_15 0x110
#define VBE_MODE_DIRECT_COLOR_24 0x115
#define VBE_MODE_DIRECT_COLOR_16 0x11A
#define VBE_MODE_DIRECT_COLOR_32 0x14C
#endif //__vbe2__
